"""
Milestone 5 — Generation
Pipeline: ... → Retrieval → Generation

Loads retrieved chunks from embed.py, builds a grounded prompt,
calls Groq's llama-3.3-70b-versatile, and returns the answer with
programmatic source attribution appended — not left to the LLM.

Grounding guarantee:
  - The system prompt FORBIDS the model from using outside knowledge.
  - Sources are appended in Python after generation, so they are always
    present and always accurate regardless of what the LLM outputs.
"""

import os
from groq import Groq
from dotenv import load_dotenv
from src.embed import retrieve

load_dotenv()

MODEL = "llama-3.3-70b-versatile"

# System prompt enforces grounding — "only" and "must not" are hard constraints,
# not suggestions. The fallback line prevents confident hallucination.
SYSTEM_PROMPT = """You are a helpful assistant for Rutgers New Brunswick students.
Answer questions using ONLY the information provided in the CONTEXT section below.
You must not use any outside knowledge, even if you are confident in it.
If the context does not contain enough information to answer the question, respond with exactly:
"I don't have enough information on that in my sources."
Be concise. Do not repeat the context back — synthesize it into a direct answer."""


def build_prompt(query: str, chunks: list[dict]) -> str:
    """
    Format retrieved chunks into a numbered CONTEXT block.
    Numbering lets the system prompt reference specific chunks if needed,
    and makes the grounding boundary visually clear in the prompt.
    """
    context_lines = []
    for i, chunk in enumerate(chunks, 1):
        context_lines.append(f"[{i}] {chunk['text']}")
    context = "\n\n".join(context_lines)

    return f"""CONTEXT:
{context}

QUESTION: {query}

ANSWER:"""


def format_sources(chunks: list[dict]) -> str:
    """
    Build a deduplicated source list programmatically.
    This runs after generation — sources are guaranteed to appear
    regardless of whether the LLM mentions them.
    """
    seen = set()
    lines = []
    for chunk in chunks:
        url = chunk.get("url", "")
        source = chunk.get("source", "unknown")
        key = url or source
        if key not in seen:
            seen.add(key)
            lines.append(f"  - {source}: {url}" if url else f"  - {source}")
    return "Sources:\n" + "\n".join(lines)


def generate(query: str, k: int = 5) -> tuple[str, str]:
    """
    Full RAG pipeline: retrieve → prompt → generate → attach sources.
    Returns (answer, sources) as separate strings.
    """
    # Step 1: retrieve relevant chunks
    chunks = retrieve(query, k=k)
    if not chunks:
        return "No relevant documents found in the index.", ""

    # Step 2: build grounded prompt
    user_prompt = build_prompt(query, chunks)

    # Step 3: call Groq
    client = Groq(api_key=os.getenv("GROQ_API_KEY"))
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_prompt},
        ],
        temperature=0.2,   # low temperature = less creative, more faithful to context
        max_tokens=512,
    )
    answer = response.choices[0].message.content.strip()

    # Step 4: build sources programmatically (not generated by the LLM)
    sources = format_sources(chunks)
    return answer, sources


# ── End-to-end test ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    test_queries = [
        "Which professor do students recommend for CS111?",
        "What are common complaints about intro CS courses at Rutgers?",
        "What study strategies do students recommend for surviving CS344?",
    ]

    for query in test_queries:
        print(f"\n{'='*60}")
        print(f"Q: {query}")
        print('='*60)
        answer, sources = generate(query)
        print(answer)
        print(sources)
